# Dockerfile.client
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build  # produces /app/dist (Vite default)

# Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# changed from 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]


COPY nginx.conf /etc/nginx/conf.d/default.conf