-- Drop existing tables in correct dependency order
DROP TABLE IF EXISTS Passwords;
DROP TABLE IF EXISTS PassUsers;
DROP TABLE IF EXISTS PassClient;

-- Create Users table
CREATE TABLE PassUsers (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  UserName VARCHAR(255) NOT NULL UNIQUE,
  UserEmail VARCHAR(255) NOT NULL UNIQUE,
  UserLogin VARCHAR(255) NOT NULL UNIQUE,
  UserRole VARCHAR(255) NOT NULL,
  UserActive BOOLEAN NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create Client table
CREATE TABLE PassClient (
  ClientID INT PRIMARY KEY AUTO_INCREMENT,
  ClientUsername VARCHAR(255) NOT NULL UNIQUE,
  ClientCompany VARCHAR(255) NOT NULL,
  ClientEmail VARCHAR(255) NOT NULL,
  ClientNotes VARCHAR(255),
  POC INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_POC FOREIGN KEY (POC) 
    REFERENCES PassUsers(UserID)
    ON DELETE CASCADE
);

-- Create Passwords table
CREATE TABLE Passwords (
  PassID INT PRIMARY KEY AUTO_INCREMENT,
  PassSite VARCHAR(255) NOT NULL,
  PassUsername VARCHAR(255) NOT NULL,
  PassHTML VARCHAR(255) NOT NULL,
  PassPW VARCHAR(255) NOT NULL,
  Client INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_Client FOREIGN KEY (Client) 
    REFERENCES PassClient(ClientID)
    ON DELETE CASCADE
);
