-- Drop and recreate schema, then seed sample data
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Passwords;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Managers;
DROP TABLE IF EXISTS Org;

SET FOREIGN_KEY_CHECKS = 1;

-- Create Organization table
CREATE TABLE Org (
  -- OrgId BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
  -- OrgId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  OrgId VARCHAR(255) PRIMARY KEY,
  OrgName VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create Manager table
CREATE TABLE Manager (
  UserId INT PRIMARY KEY AUTO_INCREMENT,
  UserName VARCHAR(255) NOT NULL UNIQUE,
  UserEmail VARCHAR(255) NOT NULL UNIQUE,
  UserRole VARCHAR(255) NOT NULL,
  UserActive BOOLEAN NOT NULL DEFAULT TRUE,
  OrgId VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_managers_org FOREIGN KEY (OrgId) REFERENCES Org(OrgId)
);

-- Create Client table
CREATE TABLE Client (
  ClientId INT PRIMARY KEY AUTO_INCREMENT,
  ClientUsername VARCHAR(255) NOT NULL UNIQUE,
  ClientCompany VARCHAR(255) NOT NULL,
  ClientEmail VARCHAR(255) NOT NULL,
  ClientNotes VARCHAR(255),
  Manager INT NOT NULL,
  OrgId VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_clients_org FOREIGN KEY (OrgId) REFERENCES Org (OrgId),
  CONSTRAINT fk_clients_manager FOREIGN KEY (Manager) REFERENCES Manager(UserId) ON DELETE CASCADE
);

-- Create Passwords table
CREATE TABLE Passwords (
  PassId INT PRIMARY KEY AUTO_INCREMENT,
  PassSite VARCHAR(255) NOT NULL,
  PassUsername VARCHAR(255) NOT NULL,
  PassHTML VARCHAR(1024) NOT NULL,
  PassPW VARCHAR(255) NOT NULL,
  Client INT,
  OrgId VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_passwords_org FOREIGN KEY (OrgId) REFERENCES Org (OrgId),
  CONSTRAINT fk_passwords_client FOREIGN KEY (Client) REFERENCES Client(ClientId) ON DELETE CASCADE
);